# Generated by Django 6.0.1 on 2026-01-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentdataset",
            name="stats",
            field=models.JSONField(default=dict),
        ),
    ]
